export const ruLang = [
  [
    "ё",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "0",
    "-",
    "=",
    "Backspace",
  ],
  [
    "Tab",
    "й",
    "ц",
    "у",
    "к",
    "е",
    "н",
    "г",
    "ш",
    "щ",
    "з",
    "х",
    "ъ",
    "/",
    "Delete",
  ],
  ["CapsLock", "ф", "ы", "в", "а", "п", "р", "о", "л", "д", "ж", "э", "Enter"],
  ["Shift", "я", "ч", "c", "м", "и", "т", "ь", "б", "ю", ".", "⇑"],
  ["Ctrl", "Alt", "SPACE", "CtrlR", "⇐", "⇓", "⇒"],
];

export const engLang = [
  [
    "`",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "0",
    "-",
    "=",
    "Backspace",
  ],
  [
    "Tab",
    "q",
    "w",
    "e",
    "r",
    "t",
    "y",
    "u",
    "i",
    "o",
    "p",
    "[",
    "]",
    "/",
    "Delete",
  ],
  ["CapsLock", "a", "s", "d", "f", "g", "h", "j", "k", "l", ";", "'", "Enter"],
  ["Shift", "z", "x", "c", "v", "b", "n", "m", ",", ".", "/", "⇑"],
  ["Ctrl", "Alt", "SPACE", "CtrlR", "⇐", "⇓", "⇒"],
];

export const ruLangCaps = [
  [
    "Ё",
    "!",
    '"',
    "№",
    ";",
    "%",
    ":",
    "?",
    "*",
    "(",
    ")",
    "_",
    "+",
    "Backspace",
  ],
  [
    "Tab",
    "Й",
    "Ц",
    "У",
    "К",
    "Е",
    "Н",
    "Г",
    "Ш",
    "Щ",
    "З",
    "Х",
    "Ъ",
    "/",
    "Delete",
  ],
  ["CapsLock", "Ф", "Ы", "В", "А", "П", "Р", "О", "Л", "Д", "Ж", "Э", "Enter"],
  ["Shift", "Я", "Ч", "С", "М", "И", "Т", "Ь", "Б", "Ю", ",", "⇑"],
  ["Ctrl", "Alt", "SPACE", "CtrlR", "⇐", "⇓", "⇒"],
];

export const engLangCaps = [
  [
    "~",
    "!",
    "@",
    "#",
    "$",
    "%",
    "^",
    "&",
    "*",
    "(",
    ")",
    "_",
    "+",
    "Backspace",
  ],
  [
    "Tab",
    "Q",
    "W",
    "E",
    "R",
    "T",
    "Y",
    "U",
    "I",
    "O",
    "P",
    "{",
    "}",
    "|",
    "Delete",
  ],
  ["CapsLock", "A", "S", "D", "F", "G", "H", "J", "K", "L", ":", '"', "Enter"],
  ["Shift", "Z", "X", "C", "V", "B", "N", "M", "<", ">", "?", "⇑", "shift"],
  ["Ctrl", "Alt", "SPACE", "CtrlR", "⇐", "⇓", "⇒"],
];

export const keyCode = [
  {
    code: "Backquote",
    ru: ruLang[0][0],
    ruCaps: ruLangCaps[0][0],
    en: engLang[0][0],
    enCaps: engLangCaps[0][0],
  },
  {
    code: "Digit1",
    ru: ruLang[0][1],
    ruCaps: ruLangCaps[0][1],
    en: engLang[0][1],
    enCaps: engLangCaps[0][1],
  },
  {
    code: "Digit2",
    ru: ruLang[0][2],
    ruCaps: ruLangCaps[0][2],
    en: engLang[0][2],
    enCaps: engLangCaps[0][2],
  },
  {
    code: "Digit3",
    ru: ruLang[0][3],
    ruCaps: ruLangCaps[0][3],
    en: engLang[0][3],
    enCaps: engLangCaps[0][3],
  },
  {
    code: "Digit4",
    ru: ruLang[0][4],
    ruCaps: ruLangCaps[0][4],
    en: engLang[0][4],
    enCaps: engLangCaps[0][4],
  },
  {
    code: "Digit5",
    ru: ruLang[0][5],
    ruCaps: ruLangCaps[0][5],
    en: engLang[0][5],
    enCaps: engLangCaps[0][5],
  },
  {
    code: "Digit6",
    ru: ruLang[0][6],
    ruCaps: ruLangCaps[0][6],
    en: engLang[0][6],
    enCaps: engLangCaps[0][6],
  },
  {
    code: "Digit7",
    ru: ruLang[0][7],
    ruCaps: ruLangCaps[0][7],
    en: engLang[0][7],
    enCaps: engLangCaps[0][7],
  },
  {
    code: "Digit8",
    ru: ruLang[0][8],
    ruCaps: ruLangCaps[0][8],
    en: engLang[0][8],
    enCaps: engLangCaps[0][8],
  },
  {
    code: "Digit9",
    ru: ruLang[0][9],
    ruCaps: ruLangCaps[0][9],
    en: engLang[0][9],
    enCaps: engLangCaps[0][9],
  },
  {
    code: "Digit0",
    ru: ruLang[0][10],
    ruCaps: ruLangCaps[0][10],
    en: engLang[0][10],
    enCaps: engLangCaps[0][10],
  },
  {
    code: "Minus",
    ru: ruLang[0][11],
    ruCaps: ruLangCaps[0][11],
    en: engLang[0][11],
    enCaps: engLangCaps[0][11],
  },
  {
    code: "Equal",
    ru: ruLang[0][12],
    ruCaps: ruLangCaps[0][12],
    en: engLang[0][12],
    enCaps: engLangCaps[0][12],
  },
  {
    code: "Backspace",
    ru: ruLang[0][13],
    ruCaps: ruLangCaps[0][13],
    en: engLang[0][13],
    enCaps: engLangCaps[0][13],
  },

  {
    code: "Tab",
    ru: ruLang[1][0],
    ruCaps: ruLangCaps[1][0],
    en: engLang[1][0],
    enCaps: engLangCaps[1][0],
  },
  {
    code: "KeyQ",
    ru: ruLang[1][1],
    ruCaps: ruLangCaps[1][1],
    en: engLang[1][1],
    enCaps: engLangCaps[1][1],
  },
  {
    code: "KeyW",
    ru: ruLang[1][2],
    ruCaps: ruLangCaps[1][2],
    en: engLang[1][2],
    enCaps: engLangCaps[1][2],
  },
  {
    code: "KeyE",
    ru: ruLang[1][3],
    ruCaps: ruLangCaps[1][3],
    en: engLang[1][3],
    enCaps: engLangCaps[1][3],
  },
  {
    code: "KeyR",
    ru: ruLang[1][4],
    ruCaps: ruLangCaps[1][4],
    en: engLang[1][4],
    enCaps: engLangCaps[1][4],
  },
  {
    code: "KeyT",
    ru: ruLang[1][5],
    ruCaps: ruLangCaps[1][5],
    en: engLang[1][5],
    enCaps: engLangCaps[1][5],
  },
  {
    code: "KeyY",
    ru: ruLang[1][6],
    ruCaps: ruLangCaps[1][6],
    en: engLang[1][6],
    enCaps: engLangCaps[1][6],
  },
  {
    code: "KeyU",
    ru: ruLang[1][7],
    ruCaps: ruLangCaps[1][7],
    en: engLang[1][7],
    enCaps: engLangCaps[1][7],
  },
  {
    code: "KeyI",
    ru: ruLang[1][8],
    ruCaps: ruLangCaps[1][8],
    en: engLang[1][8],
    enCaps: engLangCaps[1][8],
  },
  {
    code: "KeyO",
    ru: ruLang[1][9],
    ruCaps: ruLangCaps[1][9],
    en: engLang[1][9],
    enCaps: engLangCaps[1][9],
  },
  {
    code: "KeyP",
    ru: ruLang[1][10],
    ruCaps: ruLangCaps[1][10],
    en: engLang[1][10],
    enCaps: engLangCaps[1][10],
  },
  {
    code: "BracketLeft",
    ru: ruLang[1][11],
    ruCaps: ruLangCaps[1][11],
    en: engLang[1][11],
    enCaps: engLangCaps[1][11],
  },
  {
    code: "BracketRight",
    ru: ruLang[1][12],
    ruCaps: ruLangCaps[1][12],
    en: engLang[1][12],
    enCaps: engLangCaps[1][12],
  },
  {
    code: "Backslash",
    ru: ruLang[1][13],
    ruCaps: ruLangCaps[1][13],
    en: engLang[1][13],
    enCaps: engLangCaps[1][13],
  },
  {
    code: "Delete",
    ru: ruLang[1][14],
    ruCaps: ruLangCaps[1][14],
    en: engLang[1][14],
    enCaps: engLangCaps[1][14],
  },

  {
    code: "CapsLock",
    ru: ruLang[2][0],
    ruCaps: ruLangCaps[2][0],
    en: engLang[2][0],
    enCaps: engLangCaps[2][0],
  },
  {
    code: "KeyA",
    ru: ruLang[2][1],
    ruCaps: ruLangCaps[2][1],
    en: engLang[2][1],
    enCaps: engLangCaps[2][1],
  },
  {
    code: "KeyS",
    ru: ruLang[2][2],
    ruCaps: ruLangCaps[2][2],
    en: engLang[2][2],
    enCaps: engLangCaps[2][2],
  },
  {
    code: "KeyD",
    ru: ruLang[2][3],
    ruCaps: ruLangCaps[2][3],
    en: engLang[2][3],
    enCaps: engLangCaps[2][3],
  },
  {
    code: "KeyF",
    ru: ruLang[2][4],
    ruCaps: ruLangCaps[2][4],
    en: engLang[2][4],
    enCaps: engLangCaps[2][4],
  },
  {
    code: "KeyG",
    ru: ruLang[2][5],
    ruCaps: ruLangCaps[2][5],
    en: engLang[2][5],
    enCaps: engLangCaps[2][5],
  },
  {
    code: "KeyH",
    ru: ruLang[2][6],
    ruCaps: ruLangCaps[2][6],
    en: engLang[2][6],
    enCaps: engLangCaps[2][6],
  },
  {
    code: "KeyJ",
    ru: ruLang[2][7],
    ruCaps: ruLangCaps[2][7],
    en: engLang[2][7],
    enCaps: engLangCaps[2][7],
  },
  {
    code: "KeyK",
    ru: ruLang[2][8],
    ruCaps: ruLangCaps[2][8],
    en: engLang[2][8],
    enCaps: engLangCaps[2][8],
  },
  {
    code: "KeyL",
    ru: ruLang[2][9],
    ruCaps: ruLangCaps[2][9],
    en: engLang[2][9],
    enCaps: engLangCaps[2][9],
  },
  {
    code: "Semicolon",
    ru: ruLang[2][10],
    ruCaps: ruLangCaps[2][10],
    en: engLang[2][10],
    enCaps: engLangCaps[2][10],
  },
  {
    code: "Quote",
    ru: ruLang[2][11],
    ruCaps: ruLangCaps[2][11],
    en: engLang[2][11],
    enCaps: engLangCaps[2][11],
  },
  {
    code: "Enter",
    ru: ruLang[2][12],
    ruCaps: ruLangCaps[2][12],
    en: engLang[2][12],
    enCaps: engLangCaps[2][12],
  },

  {
    code: "ShiftLeft",
    ru: ruLang[3][0],
    ruCaps: ruLangCaps[3][0],
    en: engLang[3][0],
    enCaps: engLangCaps[3][0],
  },
  {
    code: "KeyZ",
    ru: ruLang[3][1],
    ruCaps: ruLangCaps[3][1],
    en: engLang[3][1],
    enCaps: engLangCaps[3][1],
  },
  {
    code: "KeyX",
    ru: ruLang[3][2],
    ruCaps: ruLangCaps[3][2],
    en: engLang[3][2],
    enCaps: engLangCaps[3][2],
  },
  {
    code: "KeyC",
    ru: ruLang[3][3],
    ruCaps: ruLangCaps[3][3],
    en: engLang[3][3],
    enCaps: engLangCaps[3][3],
  },
  {
    code: "KeyV",
    ru: ruLang[3][4],
    ruCaps: ruLangCaps[3][4],
    en: engLang[3][4],
    enCaps: engLangCaps[3][4],
  },
  {
    code: "KeyB",
    ru: ruLang[3][5],
    ruCaps: ruLangCaps[3][5],
    en: engLang[3][5],
    enCaps: engLangCaps[3][5],
  },
  {
    code: "KeyN",
    ru: ruLang[3][6],
    ruCaps: ruLangCaps[3][6],
    en: engLang[3][6],
    enCaps: engLangCaps[3][6],
  },
  {
    code: "KeyM",
    ru: ruLang[3][7],
    ruCaps: ruLangCaps[3][7],
    en: engLang[3][7],
    enCaps: engLangCaps[3][7],
  },
  {
    code: "Comma",
    ru: ruLang[3][8],
    ruCaps: ruLangCaps[3][8],
    en: engLang[3][8],
    enCaps: engLangCaps[3][8],
  },
  {
    code: "Period",
    ru: ruLang[3][9],
    ruCaps: ruLangCaps[3][9],
    en: engLang[3][9],
    enCaps: engLangCaps[3][9],
  },
  {
    code: "Slash",
    ru: ruLang[3][10],
    ruCaps: ruLangCaps[3][10],
    en: engLang[3][10],
    enCaps: engLangCaps[3][10],
  },
  {
    code: "ArrowUp",
    ru: ruLang[3][11],
    ruCaps: ruLangCaps[3][11],
    en: engLang[3][11],
    enCaps: engLangCaps[3][11],
  },
  {
    code: "ShiftRight",
    ru: ruLang[3][12],
    ruCaps: ruLangCaps[3][12],
    en: engLang[3][12],
    enCaps: engLangCaps[3][12],
  },

  {
    code: "ControlLeft",
    ru: ruLang[4][0],
    ruCaps: ruLangCaps[4][0],
    en: engLang[4][0],
    enCaps: engLangCaps[4][0],
  },
  {
    code: "AltLeft",
    ru: ruLang[4][1],
    ruCaps: ruLangCaps[4][1],
    en: engLang[4][1],
    enCaps: engLangCaps[4][1],
  },
  {
    code: "Space",
    ru: ruLang[4][2],
    ruCaps: ruLangCaps[4][2],
    en: engLang[4][2],
    enCaps: engLangCaps[4][2],
  },
  {
    code: "AltRight",
    ru: ruLang[4][3],
    ruCaps: ruLangCaps[4][3],
    en: engLang[4][3],
    enCaps: engLangCaps[4][3],
  },
  {
    code: "ArrowLeft",
    ru: ruLang[4][4],
    ruCaps: ruLangCaps[4][4],
    en: engLang[4][4],
    enCaps: engLangCaps[4][4],
  },
  {
    code: "ArrowDown",
    ru: ruLang[4][5],
    ruCaps: ruLangCaps[4][5],
    en: engLang[4][5],
    enCaps: engLangCaps[4][5],
  },
  {
    code: "ArrowRight",
    ru: ruLang[4][6],
    ruCaps: ruLangCaps[4][6],
    en: engLang[4][6],
    enCaps: engLangCaps[4][6],
  },
];
